version: '3'
services:
  web:
    build: .
    volumes:
      - .:/myapp:cached
      - bundle_cache:/usr/local/bundle
      - /Users/clay/Desktop/life/temp-images-dir:/bel-images
    command: bundle exec puma -C config/puma.rb
    env_file: .env.development
    ports:
      - "4534:4534"
  postgres:
    image: postgres
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    env_file: .env.development
    ports:
      - '5432:5432'
volumes:
  my_dbdata:
  bundle_cache: