version: '3'
services:
  db:
    image: postgres
    env_file: .env.production
  web:
    build: .
    volumes:
      - .:/myapp:cached
      - bundle_cache:/usr/local/bundle
    command: bundle exec puma -C config/puma.rb
    env_file: .env.production
    ports:
      - "3000:3000"
      - "443:443"
    depends_on:
      - db
volumes:
  bundle_cache:
