version: '3'
services:
  web:
    build: .
    volumes:
      - .:/myapp:cached
      - bundle_cache:/usr/local/bundle
    command: bundle exec puma -C config/puma.rb
    env_file: .env.development
    ports:
      - "4534:3000"
    depends_on:
      - webpacker
  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes: 
      - .:/myapp:cached
    ports:
      - "3035:3035"
  postgres:
    image: postgres
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    env_file: .env.development
    ports:
      - '34231:5432'
  redis:
    image: 'redis:3.2-alpine'
    ports:
      - '6379:6379'
volumes:
  my_dbdata:
  bundle_cache:
